version: '3'
services:
  redis-cv:
    image: redis:4.0-alpine
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=fubar
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'

  postgres-cv:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=cv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d cv"]
      interval: 10s
      timeout: 5s
      retries: 5

#  cv:
#    build: .
#    environment:
#      - PORT=4000
#      - PGHOST=postgres-cv
#      - PGPORT=5433
#      - PGUSER=postgresuser
#      - PGPASSWORD=postgrespassword
#      - PGDATABASE=cv
#      - DATABASE_URL=postgres://postgresuser:postgrespassword@postgres-cv:5433/cv
#      - REDIS=redis://:fubar@redis-cv:6380/
#      - APP_NAME=mydata-cv
#      - APM_SERVER=http://apm-server:8200
#    ports:
#      - 4000:4000
#    depends_on:
#      - postgres-cv
#      - redis-cv
